import { createFileRoute } from '@tanstack/react-router'
import { faker } from 'faker'

import { Combobox } from '~/components/ui/combobox'
import { Typography } from '~/components/ui/typography'
import type { ComboboxOption } from '~/components/ui/combobox'

export const Route = createFileRoute('/(ui)/combobox')({
  loader: () => {
    const createRandomOption = (): ComboboxOption => ({
      label: faker.internet.username(),
      value: faker.string.uuid(),
    })

    const options = faker.helpers.multiple(createRandomOption, {
      count: 1000,
    })

    return { options }
  },
  component: ComboboxExample,
})

function ComboboxExample() {
  const { options } = Route.useLoaderData()

  return (
    <div className="space-y-4">
      <Typography.H2>Shadcn Combobox + TanStack Virtual</Typography.H2>
      <Typography.P>
        Data Amount: {new Intl.NumberFormat('en-US').format(options.length)}{' '}
        (Generated by Faker.js)
      </Typography.P>
      <Combobox options={options} disabled />
    </div>
  )
}
